repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        additional_dependencies: ["ruamel.yaml>=0.18.0"]
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension
        exclude: ^\.envrc$
      - id: script-must-not-have-extension
      - id: shellcheck
  - repo: local
    hooks:
      - id: nix-build-test
        name: Nix build test
        entry: make test
        language: system
        files: ^(flake\.(nix|lock)|.*\.nix)$
        pass_filenames: false
        description: "Build system and home configurations to validate Nix files"
      - id: test-linux-deployment
        name: Test Linux deployment via Docker
        entry: make test-linux
        language: system
        files: ^(flake\.(nix|lock)|home/.*\.nix|nix/.*\.nix|lib/.*\.nix|hosts/.*/.*\.nix|config/.*\.(json|md)|test/.*)$
        pass_filenames: false
        stages: [manual]
        description: "Run Docker-based Linux deployment test (manual trigger only)"
