apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: zsh/plugins
    contents:
      - path: zsh-autosuggestions
        git:
          url: https://github.com/zsh-users/zsh-autosuggestions
          ref: master
          depth: 1
      - path: zsh-history-substring-search
        git:
          url: https://github.com/zsh-users/zsh-history-substring-search
          ref: master
          depth: 1
      - path: zsh-syntax-highlighting
        git:
          url: https://github.com/zsh-users/zsh-syntax-highlighting
          ref: master
          depth: 1
