# shellcheck shell=bash
# shellcheck external-sources=false disable=SC1091

# In login shells bash_profile is read before bash_login and profile
# The others are not read if this exists
# In interactive non-login shells, bashrc is read.
# In sh mode, profile is read...
# https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html#Bash-Startup-Files

# Basically, point this at bashrc, let it load .profile, so it can be consistent
# and then have that drop out before setting anything interactive

if [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
fi
