# shellcheck shell=bash
# shellcheck external-sources=false disable=SC1091

# see bash_profile
if [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi


+path.source \
  "$PERLBREW_ROOT/etc/bashrc" \

export DOTFILES_PATH

BASHRCD=(
  "$DOTFILES_PATH/bashrc.d"/*
  "$HOME/.bashrc_local"
)

+path.source "${BASHRCD[@]}"
