#!/bin/bash

CONFIGDIR="$HOME/.config/nalabelle/repo-autopull"
CONFIGNAME="default"
CONFIGFILE="$CONFIGNAME.conf"

if [ ! -f $CONFIGDIR/$CONFIGFILE ]; then
  if [ ! -d $CONFIGDIR ]; then
    mkdir -p $CONFIGDIR
  fi
  cat > $CONFIGDIR/$CONFIGFILE << EOF
# Configuration for repo-autopull

REPOS=(
  $HOME/repository1/
  $HOME/repository2/
)

EOF
fi

. $CONFIGDIR/$CONFIGFILE

help() {
  cat << EOF
usage: $0 options

This script pulls a list of repositories you have defined and set up.

OPTIONS:
  -h  Show this message
  -v  Output more information for debugging
  -d  Show what commands this runs

EOF
}

update() {
  if $VERBOSE; then
    echo "Updating repositories in $CONFIGDIR/$CONFIGFILE..."
  fi

  for i in "${REPOS[@]}"
  do
    if [ -d ${i} ]; then
      if $VERBOSE; then
        echo "Updating ${i}"
      fi
      if $DRYRUN; then
        echo "cd ${i}"
        echo "git pull"
        echo "cd -"
      else
        cd ${i}
        local RESULT=`git pull`
        local TRASH=`cd -`

        if $VERBOSE; then
          echo $RESULT;
        fi
      fi
    else
      if $VERBOSE; then
        echo "Couldn't find folder: ${i}"
      fi
    fi
  done
}

VERBOSE=false
DRYRUN=false

while getopts "hvd" OPTION; do
  case $OPTION in
    h)
      help
      exit 0
      ;;
    v)
      VERBOSE=true
      ;;
    d)
      DRYRUN=true
      ;;
    ?)
      help
      exit 0
      ;;
  esac
done

shift $((OPTIND-1))

if [ ! -z $1 ]; then
  #Build and load config from supplied config name
  CONFIGNAME=${1}
  CONFIGFILE="$CONFIGNAME.conf"

  if $VERBOSE; then
    echo "Loading $CONFIGDIR/$CONFIGFILE..."
  fi

  if [ ! -f $CONFIGDIR/$CONFIGFILE ]; then
    echo "Invalid configuration file"
    help
    exit 1
  fi

  . $CONFIGDIR/$CONFIGFILE
fi

update

exit 0
