# vim:filetype=zsh

ZDOTDIR="$HOME/.config/zsh"

# https://github.com/jeffreytse/zsh-vi-mode
#. $ZDOTDIR/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
bindkey -v
# allow backspacing over characters to left
bindkey -v '^?' backward-delete-char

# https://github.com/zsh-users/zsh-autosuggestions
. $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# https://github.com/Tarrasch/zsh-bd
. $ZDOTDIR/plugins/zsh-bd/bd.zsh

# https://github.com/zsh-users/zsh-syntax-highlighting
. $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# https://linux.die.net/man/1/zshoptions

# Convenience
setopt autocd

# Globbing
setopt nocaseglob
setopt extendedglob
setopt globdots
# Sends unmatched globs to the command
setopt no_nomatch

# History
HISTFILE="$ZDOTDIR/zsh_history"
# How many commands in the history file
SAVEHIST=5000
# How many commands in session history
HISTSIZE=2000
setopt appendhistory
setopt histexpiredupsfirst
setopt histfindnodups
setopt histignorealldups
setopt histignoredups
setopt histnostore
setopt histreduceblanks
setopt incappendhistory
setopt sharehistory

# Put the !! command in the prompt for changing
setopt histverify

# Corrections
setopt correct

key=(
  BackSpace  "${terminfo[kbs]}"
  Home       "${terminfo[khome]}"
  End        "${terminfo[kend]}"
  Insert     "${terminfo[kich1]}"
  Delete     "${terminfo[kdch1]}"
  Up         "${terminfo[kcuu1]}"
  Down       "${terminfo[kcud1]}"
  Left       "${terminfo[kcub1]}"
  Right      "${terminfo[kcuf1]}"
  PageUp     "${terminfo[kpp]}"
  PageDown   "${terminfo[knp]}"
)




zstyle ':vcs_info:*' enable git svn


#zstyle ':vcs_info:git*' formats "%r/%S %b (%a) %m%u%c "
zstyle ':vcs_info:git*' formats '%{%F{yellow}%} [%b] %a%m%u%c%{%F%}'
#zsytle '

# Prompt

setopt prompt_subst
PROMPT='%{%F{032}%}%n@%m%{%F%}:%{$fg[blue]%}%0~%{%F{000}%}${vcs_info_msg_0_}%{$fg[white]%}%# %{%f%}'
#\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]${_ps1_git_prompt-}\n\$ "

precmd() {
  vcs_info
  colors
  promptinit
}

autoload -U promptinit
autoload -U colors
autoload -Uz vcs_info
autoload -U compinit; compinit

command -v direnv > /dev/null 2>&1 && eval "$(direnv hook zsh)"
