k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: production-20220425
  currentCluster: production-20220425
  clusters:
    dev-dataeng:
      namespace:
        active: data-eng-healthchecks
        lockFavorites: false
        favorites:
        - airflow-dev
        - data-eng-healthchecks
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    production-20220425:
      namespace:
        active: data-eng-healthchecks
        lockFavorites: false
        favorites:
        - all
        - traefik-production
        - data-eng-healthchecks
        - default
      view:
        active: secrets
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    staging-20220401:
      namespace:
        active: data-eng-healthchecks
        lockFavorites: false
        favorites:
        - airflow-staging
        - all
        - data-eng-healthchecks
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/wm/2pwzspns7y50s78_ppf321h80000gn/T/k9s-screens-nalabelle
