#!/bin/bash

if [ -d "$HOME/.linuxbrew" ]; then
  eval "$("$HOME"/.linuxbrew/bin/brew shellenv)"
fi

if [ -d /opt/homebrew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if command -v brew > /dev/null 2>&1; then
  _source "$(brew --prefix)/etc/bash_completion.d"
fi
