#!/bin/bash

#BREW ASDF
if command -v brew > /dev/null 2>&1; then
  asdf_path="$(brew --prefix)/opt/asdf/libexec/asdf.sh"
  +path.source "$asdf_path"
fi


_asdf_scripts=(
  "$HOME/.asdf/asdf.sh"
  "$HOME/.asdf/plugins/java/set-java-home.bash"
  "$HOME/.asdf/completions/asdf.bash"
)

set +u
+path.source "${_asdf_scripts[@]}"
set -u

unset _asdf_scripts
