#!/bin/bash

ADDITIONAL_PATHS=(
  "$DOTFILES_PATH/bin"
  #osx: homebrew mysql-client
  /usr/local/opt/mysql-client/bin
)

BASH_COMPLETION=(
  /etc/bash_completion
  /usr/share/bash-completion/bash_completion
  /usr/local/etc/profile.d/bash_completion.sh
  /usr/local/etc/bash_completion.d
  "$HOME/.bash-completion"
  "$HOME/.bash-completion.d"
  "$HOME/.git-completion.bash"
)

ADDITIONAL_SCRIPTS=(
  #osx: homebrew asdf
  # maybe move to something using `brew --prefix`?
  /usr/local/opt/asdf/asdf.sh
)

_path "${ADDITIONAL_PATHS[@]}"
_source "${BASH_COMPLETION[@]}"
_source "${ADDITIONAL_SCRIPTS[@]}"

export GOPATH="$HOME/go"
_path "${GOPATH}/bin"

#export PERLBREW_ROOT="$HOME/.perlbrew"
#_source "$PERLBREW_ROOT/etc/bashrc"

export PYTHONPYCACHEPREFIX="$HOME/.cache/pycache"

# If not running interactively, bail here
if [ -z "$PS1" ]; then
  return
fi

# share history across all sessions
export SHELL_SESSION_HISTORY=0
# don't put duplicate lines in the history
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#use vi mode instead of emacs
set -o vi
#remove escape lag
export KEYTIMEOUT=1

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

# set color
color_prompt=
case $TERM in
  *'color'* )
    color_prompt=yes
    ;;
esac

if [ -z "$color_prompt" ]; then
  _tput="$(which tput)"
  if [ -n "$_tput" ] && [ -x /usr/bin/tput ]; then
    if tput setaf 1 >&/dev/null; then
      color_prompt=yes
    else
      if [ "$($_tput colors)" -gt 8 ]; then
        color_prompt=yes
      fi
    fi
  fi
fi

if [ "$color_prompt" = yes ]; then
  # enable color support of ls and also add handy aliases
  if [ -x /usr/bin/dircolors ]; then
    if [ -r "$HOME/.dircolors" ]; then
      eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    fi
    alias ls='ls --color=always'
    alias grep='grep --color=always'
  fi

  # enable color support of ls for OSX
  if [[ "$OSTYPE" == "darwin"* || "$OSTYPE" == "freebsd"* ]]; then
    alias ls='CLICOLOR_FORCE=1 ls -G'
    alias grep='grep --color=always'
    alias less='less -F -S -R -M -i'
  fi

  if diff --help | grep '\-\-color' > /dev/null || false; then
    alias diff='diff --color=always'
  fi

  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
  PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt

# let's color our man pages
# from archlinux wiki:
man() {
  env LESS_TERMCAP_mb=$(printf "\e[1;31m") \
      LESS_TERMCAP_md=$(printf "\e[1;31m") \
      LESS_TERMCAP_me=$(printf "\e[0m") \
      LESS_TERMCAP_se=$(printf "\e[0m") \
      LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
      LESS_TERMCAP_ue=$(printf "\e[0m") \
      LESS_TERMCAP_us=$(printf "\e[1;32m") \
      man "$@"
}

cd-git-root() {
  cd "$(git rev-parse --show-toplevel)" || return
}

cd-dotfiles() {
  cd "$DOTFILES_PATH" || return
}

docker-pause-all() {
  local containers
  mapfile -t containers < <(docker ps -aq)
  docker pause "${containers[@]}"
}

docker-resume-all() {
  local containers
  mapfile -t containers < <(docker ps -aq)
  docker unpause "${containers[@]}"
}

# known-hosts autocomplete
complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | \
    sed -e s/,.*//g | uniq | grep -v "\["`;)" ssh

unset ADDITIONAL_PATHS
unset BASH_COMPLETION

