#!/bin/bash

# If not running interactively, bail here
if [ -z "$PS1" ]; then
  return
fi

# Bash Completions
+path.source \
  /etc/bash_completion \
  /usr/share/bash-completion/bash_completion \
  /usr/local/etc/profile.d/bash_completion.sh \
  /usr/local/etc/bash_completion.d/* \

# append to the history file, don't overwrite it
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#use vi mode instead of emacs
set -o vi

docker-pause-all() {
  local containers
  mapfile -t containers < <(docker ps -aq)
  docker pause "${containers[@]}"
}

docker-resume-all() {
  local containers
  mapfile -t containers < <(docker ps -aq)
  docker unpause "${containers[@]}"
}

# known-hosts autocomplete
complete -W "$(cut -f 1 -d ' ' "$HOME/.ssh/known_hosts" | \
  sed -e s/,.*//g | uniq | grep -Ev '^[^A-Za-z]|\[')" ssh

unset ADDITIONAL_PATHS
unset BASH_COMPLETION
