#!/bin/bash

if command -v flux > /dev/null; then
  #shellcheck disable=SC1090
  . <(flux completion bash)
fi

if command -v kubectl > /dev/null; then
  source <(kubectl completion bash)
fi

if command -v velero > /dev/null; then
  source <(velero completion bash)
fi

if command -v docker-compose > /dev/null; then
  # shellcheck source=../bash_completion/docker-compose
  . "$DOTFILES_PATH"/bash_completion/docker-compose
fi

if command -v perlbrew > /dev/null; then
  # shellcheck source=../bash_completion/perlbrew
  . "$DOTFILES_PATH"/bash_completion/perlbrew
fi

if command -v terraform > /dev/null; then
  complete -C terraform terraform
fi
