#!/bin/bash

if [ -d "$HOME/.linuxbrew" ]; then
  eval "$("$HOME"/.linuxbrew/bin/brew shellenv)"
fi

if [[ -z "$(command -v brew)" ]]; then
  return
fi

function _os_prefix() {
  if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "osx"
  else
    echo "linux"
  fi
}

function brew() {
  local arg=("$@")
  local cmd=$1
  local dotfile_list

  dotfile_list="$DOTFILES_PATH/$(_os_prefix)/brew"

  if [ ! -f "$dotfile_list" ]; then
    return
  fi

  command brew "${arg[@]}"

  retval=$?
  if [ "$retval" -ne 0 ]; then
    return
  fi

  case $cmd in
    install )
      shift;
      echo "logging changes to $dotfile_list"
      echo "$*" >> "$dotfile_list"
      sort -o "$dotfile_list" "$dotfile_list"
      ;;
    uninstall )
      shift;
      echo "logging changes to $dotfile_list"
      sed -i.bak "/^${*}/d" "$dotfile_list"
      ;;
    *)
      ;;
  esac
}

