#!/bin/bash

if [ -n "$(command -v brew)" ]; then
  HOMESHICK_DIR="$(brew --prefix)/opt/homeshick"
  if [ -d "$HOMESHICK_DIR" ]; then
    export HOMESHICK_DIR
    #shellcheck disable=SC1090
    source "$HOMESHICK_DIR/homeshick.sh"
  else
    unset HOMESHICK_DIR
  fi
fi

if [ -d "$HOME/.homesick/repos/homeshick" ]; then
  _source "$HOME/.homesick/repos/homeshick/homeshick.sh"
  _source "$HOME/.homesick/repos/homeshick/completions/homeshick-completion.bash"
fi

if [ -n "$(command -v homeshick)" ]; then
  homeshick --quiet refresh
fi

