#!/bin/bash
debian_chroot=${debian_chroot:-}
color_prompt=${color_prompt:-}

__git_prompt() {
  local _exports=(
    GIT_PS1_SHOWCOLORHINTS=1
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWSTASHSTATE=1
    GIT_PS1_SHOWUNTRACKEDFILES=1
    GIT_PS1_SHOWUPSTREAM=1
    GIT_PS1_STATESEPARATOR=""
  )
  local _monkey_patch
  _monkey_patch="$( declare -pf __git_ps1 | \
    awk '/GIT_PS1_SHOWCOLORHINTS/ { print "    __git_ps1_colorize_gitstring;" } { print }' )"

  local _result
  _result="$( \
    eval "$_monkey_patch"; \
    export "${_exports[@]}"; \
    __git_ps1 ":%s" | \
    sed 's/\\\[/\\001/g;s/\\\]/\\002/g')"
  echo -e "$_result"
}

if [ -n "$(which git)" ]; then
  #shellcheck disable=SC2016
  _ps1_git_prompt='$(__git_prompt)'
fi

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi
if [ -n "${debian_chroot:-}" ]; then
  _ps1_debian_prompt=${debian_chroot:+($debian_chroot)}
fi

if [ "$color_prompt" = yes ]; then
  PS1="${_ps1_debian_prompt-}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]${_ps1_git_prompt-}\n\$ "
else
  PS1="${_ps1_debian_prompt-}\u@\h:\w\$ "
fi

unset _ps1_git_prompt || true
unset color_prompt
