
# tap repositories and their packages

tap "homebrew/core"
brew "asdf"
brew "direnv"
brew "fzf"
brew "jq"
brew "mkcert"
brew "poetry"
brew "pre-commit"
brew "python"

# kubernetes
brew "k9s"
brew "kubectl"
brew "krew"
brew "fluxctl"
