name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run pre-commit
        run: nix develop --command pre-commit run --all-files --show-diff-on-failure

  build-linux:
    needs: pre-commit
    name: Build Linux Hosts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build chandler
        run: nix build .#homeConfigurations."nalabelle@chandler".activationPackage

      - name: Build doyle
        run: nix build .#homeConfigurations."nalabelle@doyle".activationPackage

  build-darwin:
    needs: pre-commit
    name: Build Darwin Host (tennyson)
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build tennyson system
        run: nix build .#darwinConfigurations.tennyson.system
