name: Darwin Build Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-darwin:
    name: Build Darwin Configurations (${{ matrix.config }})
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        config: [tennyson, bst]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix (Determinate Systems)
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build Darwin configuration
        run: nix build .#darwinConfigurations.${{ matrix.config }}.system
