name: Test Home Configurations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-home:
    name: Build Home Configurations (${{ matrix.config }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - config: 'nalabelle@twain'
            runner: ubuntu-latest
          - config: nalabelle
            runner: ubuntu-latest
          - config: 'nalabelle@bst'
            runner: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build home configuration ${{ matrix.config }}
        run: nix build .#homeConfigurations.${{ matrix.config }}.activationPackage

      - name: Prepare user and home directory for ${{ matrix.config }}
        run: |
          if [[ "${{ matrix.runner }}" == "macos-15" ]]; then
            sudo dscl . -create /Users/nalabelle
            sudo dscl . -create /Users/nalabelle UserShell /bin/bash
            sudo dscl . -create /Users/nalabelle RealName "nalabelle"
            sudo dscl . -create /Users/nalabelle UniqueID "505"
            sudo dscl . -create /Users/nalabelle PrimaryGroupID 20
            sudo dscl . -create /Users/nalabelle NFSHomeDirectory /Users/nalabelle
            sudo mkdir -p /Users/nalabelle
            sudo chown nalabelle:staff /Users/nalabelle
          else
            sudo useradd -m -u 1500 -s /bin/bash nalabelle || true
            sudo mkdir -p /home/nalabelle
            sudo chown nalabelle:nalabelle /home/nalabelle
            # Remove default shell files that interfere with Home Manager
            sudo rm -f /home/nalabelle/.profile /home/nalabelle/.bash_profile /home/nalabelle/.bashrc
          fi

      - name: Activate home configuration ${{ matrix.config }}
        run: sudo -u nalabelle -H ./result/activate

      - name: Debug deployed files
        run: |
          echo "=== Debugging file deployment ==="
          echo "Files in nalabelle home directory:"
          sudo find /home/nalabelle -type f -name "*.json" 2>/dev/null || true
          sudo find /Users/nalabelle -type f -name "*.json" 2>/dev/null || true
          echo "XDG config directory contents:"
          sudo ls -la /home/nalabelle/.config/ 2>/dev/null || true
          sudo ls -la /Users/nalabelle/.config/ 2>/dev/null || true
          echo "Application Support directory contents:"
          sudo ls -la "/Users/nalabelle/Library/Application Support/" 2>/dev/null || true

      - name: Run native Kilo Code verification
        run: sudo -u nalabelle -H test/verify "${{ matrix.config }}"
